### PR TITLE
Added some stuff to make it simpler to understand

### PR DESCRIPTION
**Pull request by EduardoJTR**

### CODE REVIEW

**Comment by EduardoJTR** [comment]
Please accept

**Comment by BaseMax** [comment]
```
Enter the first digit
```

you need to change first to second for second numbers.

**Comment by EduardoJTR** [comment]
Ok, once i get home i will.

Em seg, 19 de set de 2022 01:23, Max Base ***@***.***>
escreveu:

**Comment by EduardoJTR** [comment]
I changed it, do i have to make another pull request or can you see the changes? sorry, im new to GitHub

**Comment by BaseMax** [comment]
Thanks.

**Pull request merged**
